name: Jest Tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Global Dependencies
        run: npm install pnpm@7.25.0 -g
      - name: Install Dependencies
        run: pnpm install

      - name: Run Jest Tests
        run: pnpm exec jest --coverage --updateSnapshot
